using CRM.Domain.Enums;

namespace CRM.Domain.Entities
{
    public class Report
    {
        public int ReportId { get; set; }

        public string Title { get; set; } = string.Empty; // ✅ Added

        public ReportType ReportType { get; set; } // ✅ Enum
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        // 🔗 Generated By
        public int GeneratedByUserId { get; set; }
        public User GeneratedByUser { get; set; } = null!;
    }
}
